apiVersion: batch/v1
kind: Job
metadata:
  name: run-mnist-pipeline
  namespace: argouser
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        job-name: run-mnist-pipeline
    spec:
      serviceAccountName: pipeline-sa-runner 
      restartPolicy: Never
      containers:
        - name: pipeline-runner-container
          image: zakariaanzid/mnist:latest
          command: [python, /app/kbf-run.py]
          env:
            - name: KF_PIPELINES_SA_TOKEN_PATH
              value: /var/run/secrets/kfp/token
          volumeMounts:
            - name: kfp-token
              mountPath: /var/run/secrets/kfp
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: kfp-token
          secret:
            secretName: pipeline-sa-token
